name       : konsole
version    : 18.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/konsole-18.04.3.tar.xz : 37682f952b5905231832ade3e373406775a4d1f73665baceb5d6e62b5dfaa002
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
    - Unicode-TOU
component  : desktop.kde.core
optimize   : lto
summary    : KDE's terminal emulator
description: |
    Konsole is a terminal program for KDE. As well as being a standalone program, it is also used by other KDE programs such as the Kate editor and KDevelop development environment to provide easy access to a terminal window.
patterns   : /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kpty-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Solus-tweaks-to-the-default-config.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
